### ISSUE TITLE
MSVS2017: C1091 string exceeds 65535 bytes in length

### ISSUE THREAD

**Issue by dafanasiev** [vozlt/nginx-module-sts#1]
Just for fun I try to compile nginx with you module in VS2017 RTM (want to debug some piece of code), but cl say me C1091 :-(

Problem in `NGX_HTTP_STREAM_SERVER_TRAFFIC_STATUS_HTML_DATA`  - defined string too long.
I think you can review string embedding mechanism (if you want).

Generator  script  (without perl deps):
```
#!/bin/bash

if [[ $# -ne 2 ]]; then
    echo "Usage: $0 FILENAME VARNAME"
    exit 1
fi
file=$1
cname=$2

if [[ ! -f "$file" ]]; then
    echo "File not found: $file"
    exit 1
fi

echo "static unsigned char $cname[] = {"
hexdump -v -e '" " 16/1 "  0x%02x, " "\n"' $file | \
   sed -e '$s/0x  ,//g'
echo "};"
```

Dont forget **double-check** `sizeof(xxx)` macros in sources if apply...

**Comment by vozlt** [comment]
Thanks for suggesting it.
I fixed it.
Please test if the C1091 occur when compiling in the latest commit.

Latest commit: https://github.com/vozlt/nginx-module-sts/commit/9d5c74eb5ebd5a0a28023d1be15f0022f46585fc

**Comment by dafanasiev** [comment]
Some issues:

- `sizeof("123") != sizeof( char[] {'1','2','3'} )`  - did you forget about NULL term in char string?
(as I see you calc size of array in `ngx_http_stream_server_traffic_status_display.c:360`)
- VS use precompiled headers, so every `.c` file must contains `#include <ngx_config.h>` at the top
- also uninitialized `key.data`, so add `key.data = NULL;` after `ngx_http_stream_server_traffic_status_display.c:646`

and after that it look like ok.

**Comment by vozlt** [comment]
OK, you are right. :laughing:
I fixed it.
1. added NULL into char array.
2. included `ngx_config.h` into `ngx_http_stream_server_traffic_status_module.h` and `ngx_http_stream_server_traffic_status_string.c` files. (Please check if an compile error occurs.)
3. initialized key variable by `ngx_memzero()`.

Please test.
Latest commit: https://github.com/vozlt/nginx-module-sts/commit/391a4de3d483a0e23eac3e5d8f40d1cbbd9666ec

**Comment by dafanasiev** [comment]
2) PCH feature only work when include added to every .c file (not .h), so now i cant build without modifications..

**Comment by vozlt** [comment]
OK, I added it.
Please check it.
FYI. I'm just curious. Is it possible to disable pre-compiled headers feature when compiling?

Latest commit: https://github.com/vozlt/nginx-module-sts/commit/a5d65d021d224bd7ba68a435023ca36f6de9354e

**Comment by dafanasiev** [comment]
Yeah, now all ok.

Yes, you can disable using PCH using `-Y*` options (see [here](https://msdn.microsoft.com/en-us/library/b4w02hte.aspx)), but by default nginx configure script generate makefile with `-Yu`:
```
....
objs/ngx_modules.obj:	$(CORE_DEPS) \
	objs/ngx_modules.c
	$(CC) -c $(CFLAGS) -Yungx_config.h -Fpobjs/ngx_config.pch $(ALL_INCS) \
		-Foobjs/ngx_modules.obj \
		objs/ngx_modules.c
....
```
File `ngx_modules.c ` contains references to all modules: kernel and that was added with `--add-module` args (when you call `configure.sh`).
So, by default nginx build use precompiled headers when compile via MSVC.
